apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  generation: 1
  name: grafana
  namespace: default
spec:
  gateways:
  - airmap-internal-services
  hosts:
  - grafana.test.k8s.airmap.io
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: kube-prometheus-grafana.monitoring.svc.cluster.local
    timeout: 60s
