apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: canarydeployments.app.kip.com
spec:
  group: app.kip.com
  names:
    kind: CanaryDeployment
    listKind: CanaryDeploymentList
    plural: canarydeployments
    singular: canarydeployment
  scope: Namespaced
  version: v1alpha1
  subresources:
    status: {}
