apiVersion: apps/v1
kind: Deployment
metadata:
  name: kip
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kip
  template:
    metadata:
      labels:
        name: kip
    spec:
      serviceAccountName: kip
      containers:
        - name: kip
          # Replace this with the built image name
          image: lp150189/kip-operator
          ports:
          - containerPort: 60000
            name: metrics
          command:
          - kip
          imagePullPolicy: Always
          readinessProbe:
            exec:
              command:
                - stat
                - /tmp/operator-sdk-ready
            initialDelaySeconds: 4
            periodSeconds: 10
            failureThreshold: 1
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "kip"
